# Generated by Django 5.1.7 on 2025-03-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSignals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=100)),
                ('signal', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('sinal', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Historical Signal',
                'verbose_name_plural': 'Historical Signals',
                'db_table': 'sinais"."historical_signals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSignalsShort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=100)),
                ('signal', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('sinal', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Historical Signal Short',
                'verbose_name_plural': 'Historical Signals Short',
                'db_table': 'sinais"."historical_signals_short',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=100)),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('exit_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('quantity', models.FloatField()),
                ('profit', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('sinal', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'sinais"."trades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TradesShort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=100)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('profit', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('sinal', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Trade Short',
                'verbose_name_plural': 'Trades Short',
                'db_table': 'sinais"."trades_short',
                'managed': False,
            },
        ),
    ]
