# Generated by Django 5.1.7 on 2025-08-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("signal", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("timestamp", models.DateTimeField()),
                ("sinal", models.IntegerField()),
                ("percentage", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Historical Signal",
                "verbose_name_plural": "Historical Signals",
                "db_table": "sinais.historical_signals",
            },
        ),
        migrations.CreateModel(
            name="HistoricalSignalShort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("signal", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("timestamp", models.DateTimeField()),
                ("sinal", models.IntegerField()),
                ("percentage", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Historical Signal Short",
                "verbose_name_plural": "Historical Signals Short",
                "db_table": "sinais.historical_signals_short",
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("entry_price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("exit_price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("quantity", models.FloatField()),
                ("profit", models.FloatField()),
                ("type", models.CharField(max_length=50)),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField()),
                ("sinal", models.IntegerField()),
                ("percentage", models.FloatField(blank=True, null=True)),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="sinais.historicalsignal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade",
                "verbose_name_plural": "Trades",
                "db_table": "sinais.trades",
            },
        ),
        migrations.CreateModel(
            name="TradeShort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("entry_price", models.FloatField()),
                ("exit_price", models.FloatField()),
                ("quantity", models.FloatField()),
                ("profit", models.FloatField()),
                ("type", models.CharField(max_length=50)),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField()),
                ("sinal", models.IntegerField()),
                ("percentage", models.FloatField(blank=True, null=True)),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades_short",
                        to="sinais.historicalsignalshort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Short",
                "verbose_name_plural": "Trades Short",
                "db_table": "sinais.trades_short",
            },
        ),
        migrations.DeleteModel(
            name="HistoricalSignals",
        ),
        migrations.DeleteModel(
            name="HistoricalSignalsShort",
        ),
        migrations.DeleteModel(
            name="Trades",
        ),
        migrations.DeleteModel(
            name="TradesShort",
        ),
    ]
